#! /bin/sh

set -e

. /usr/share/debconf/confmodule
db_version 2.0

action="$1"
oldversion="$2"

umask 022


setup_user() {
        if ! getent passwd golemu >/dev/null; then
                adduser --quiet --system --no-create-home --home /var/lib/golemu --shell /usr/sbin/nologin golemu
                mkdir -p -m 700 /var/cache/golemu/ /var/lib/golemu/ /var/run/golemu/
                chown golemu:golemu /var/cache/golemu /var/lib/golemu /var/run/golemu
        fi
}

if [ "$action" = configure ]; then
	setup_user
fi

systemctl enable gu-provider
systemctl start gu-provider

